[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["bash setup-codespace.sh", "npm install --prefix client"]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "node apply-production.mjs && node server/index.mjs"
